#pragma once

// =============================================================================
// theme_loader.hpp — Load terminal_colors.json for the Xell Terminal IDE
// =============================================================================
// Parses the JSON generated by gen_xell_grammar.py to provide:
//   - Editor UI colors (background, gutter, tabs, status bar, etc.)
//   - Token scope → Color mapping (for syntax highlighting)
//   - TokenType enum name → scope mapping (for the highlighter bridge)
//
// Falls back to built-in defaults if no JSON file is found.
// =============================================================================

#include <string>
#include <unordered_map>
#include <vector>
#include <fstream>
#include <sstream>
#include <iostream>
#include <filesystem>
#include <algorithm>
#include "../terminal/types.hpp"

namespace fs = std::filesystem;

namespace xterm
{

    // ─── A simple JSON token/value extractor (no library dependency) ─────────
    // We only need to parse flat objects and arrays of flat objects.
    // This is NOT a full JSON parser — it handles the specific shape of
    // terminal_colors.json.

    struct ThemeData
    {
        // Editor UI colors
        std::unordered_map<std::string, Color> ui;

        // TextMate scope → Color + style
        struct TokenStyle
        {
            Color fg;
            bool bold = false;
            bool italic = false;
        };
        std::unordered_map<std::string, TokenStyle> scopeColors;

        // TokenType enum name → scope string (e.g. "FN" → "keyword.declaration.function.xell")
        std::unordered_map<std::string, std::string> tokenTypeMap;

        // Builtin function name → scope string (e.g. "print" → "support.function.builtin.xell")
        // Generated by gen_xell_grammar.py from C++ source analysis — single source of truth.
        std::unordered_map<std::string, std::string> builtinNames;

        bool loaded = false;
    };

    // ─── Hex color parser ────────────────────────────────────────────────────

    inline Color parseHexColor(const std::string &hex)
    {
        if (hex.empty() || hex[0] != '#')
            return Color::default_fg();

        unsigned int val = 0;
        std::string h = hex.substr(1);

        // Handle #RRGGBB and #RRGGBBAA
        if (h.size() == 6 || h.size() == 8)
        {
            std::istringstream iss(h);
            iss >> std::hex >> val;

            if (h.size() == 8)
            {
                uint8_t r = (val >> 24) & 0xFF;
                uint8_t g = (val >> 16) & 0xFF;
                uint8_t b = (val >> 8) & 0xFF;
                uint8_t a = val & 0xFF;
                return {r, g, b, a};
            }
            else
            {
                uint8_t r = (val >> 16) & 0xFF;
                uint8_t g = (val >> 8) & 0xFF;
                uint8_t b = val & 0xFF;
                return {r, g, b, 255};
            }
        }
        return Color::default_fg();
    }

    // ─── Minimal JSON helpers ────────────────────────────────────────────────

    namespace json_helper
    {
        // Skip whitespace
        inline void skip_ws(const std::string &s, size_t &pos)
        {
            while (pos < s.size() && (s[pos] == ' ' || s[pos] == '\t' ||
                                      s[pos] == '\n' || s[pos] == '\r'))
                pos++;
        }

        // Read a quoted string, return content (unescaped)
        inline std::string read_string(const std::string &s, size_t &pos)
        {
            if (pos >= s.size() || s[pos] != '"')
                return "";
            pos++; // skip opening quote
            std::string result;
            while (pos < s.size() && s[pos] != '"')
            {
                if (s[pos] == '\\' && pos + 1 < s.size())
                {
                    pos++;
                    result += s[pos];
                }
                else
                {
                    result += s[pos];
                }
                pos++;
            }
            if (pos < s.size())
                pos++; // skip closing quote
            return result;
        }

        // Read a boolean or string value
        inline std::string read_value(const std::string &s, size_t &pos)
        {
            skip_ws(s, pos);
            if (pos < s.size() && s[pos] == '"')
                return read_string(s, pos);

            // Read bare token (true, false, null, number)
            std::string result;
            while (pos < s.size() && s[pos] != ',' && s[pos] != '}' &&
                   s[pos] != ']' && s[pos] != ' ' && s[pos] != '\n')
            {
                result += s[pos++];
            }
            return result;
        }

        // Skip to next key-value in an object (past comma)
        inline void skip_comma(const std::string &s, size_t &pos)
        {
            skip_ws(s, pos);
            if (pos < s.size() && s[pos] == ',')
                pos++;
        }

        // Find a top-level key in a JSON string and position after the ':'
        inline bool find_key(const std::string &s, const std::string &key, size_t &pos)
        {
            std::string needle = "\"" + key + "\"";
            auto found = s.find(needle, pos);
            if (found == std::string::npos)
                return false;
            pos = found + needle.size();
            skip_ws(s, pos);
            if (pos < s.size() && s[pos] == ':')
                pos++;
            skip_ws(s, pos);
            return true;
        }

        // Parse a flat object { "key": "value", ... } into a map
        inline std::unordered_map<std::string, std::string>
        parse_flat_object(const std::string &s, size_t &pos)
        {
            std::unordered_map<std::string, std::string> result;
            skip_ws(s, pos);
            if (pos >= s.size() || s[pos] != '{')
                return result;
            pos++; // skip {

            while (pos < s.size())
            {
                skip_ws(s, pos);
                if (s[pos] == '}')
                {
                    pos++;
                    break;
                }

                std::string key = read_string(s, pos);
                skip_ws(s, pos);
                if (pos < s.size() && s[pos] == ':')
                    pos++;
                skip_ws(s, pos);
                std::string val = read_value(s, pos);
                result[key] = val;
                skip_comma(s, pos);
            }
            return result;
        }

        // Parse a flat string array ["a", "b", "c"] → vector<string>
        inline std::vector<std::string>
        parse_string_array(const std::string &s, size_t &pos)
        {
            std::vector<std::string> result;
            skip_ws(s, pos);
            if (pos >= s.size() || s[pos] != '[')
                return result;
            pos++; // skip [

            while (pos < s.size())
            {
                skip_ws(s, pos);
                if (s[pos] == ']')
                {
                    pos++;
                    break;
                }

                std::string val = read_string(s, pos);
                if (!val.empty())
                    result.push_back(val);
                skip_comma(s, pos);
            }
            return result;
        }

    } // namespace json_helper

    // ─── Theme loader ────────────────────────────────────────────────────────

    inline ThemeData loadTheme(const std::string &jsonPath)
    {
        ThemeData theme;

        if (!fs::exists(jsonPath))
        {
            std::cerr << "[theme] File not found: " << jsonPath << "\n";
            return theme;
        }

        std::ifstream f(jsonPath);
        std::string content((std::istreambuf_iterator<char>(f)),
                            std::istreambuf_iterator<char>());

        // ── Parse editor_ui ──────────────────────────────────────────────
        {
            size_t pos = 0;
            if (json_helper::find_key(content, "editor_ui", pos))
            {
                auto uiMap = json_helper::parse_flat_object(content, pos);
                for (auto &[k, v] : uiMap)
                    theme.ui[k] = parseHexColor(v);
            }
        }

        // ── Parse token_colors array ─────────────────────────────────────
        {
            size_t pos = 0;
            if (json_helper::find_key(content, "token_colors", pos))
            {
                // pos should be at '['
                json_helper::skip_ws(content, pos);
                if (pos < content.size() && content[pos] == '[')
                {
                    pos++; // skip [
                    while (pos < content.size())
                    {
                        json_helper::skip_ws(content, pos);
                        if (content[pos] == ']')
                        {
                            pos++;
                            break;
                        }

                        auto obj = json_helper::parse_flat_object(content, pos);
                        if (obj.count("scope") && obj.count("fg"))
                        {
                            ThemeData::TokenStyle style;
                            style.fg = parseHexColor(obj["fg"]);
                            style.bold = (obj.count("bold") && obj["bold"] == "true");
                            style.italic = (obj.count("italic") && obj["italic"] == "true");
                            theme.scopeColors[obj["scope"]] = style;
                        }
                        json_helper::skip_comma(content, pos);
                    }
                }
            }
        }

        // ── Parse token_type_map ─────────────────────────────────────────
        {
            size_t pos = 0;
            if (json_helper::find_key(content, "token_type_map", pos))
            {
                auto typeMap = json_helper::parse_flat_object(content, pos);
                theme.tokenTypeMap = std::move(typeMap);
            }
        }

        // ── Parse builtin_names: { "scope": ["name1", ...], ... } ────────
        {
            size_t pos = 0;
            if (json_helper::find_key(content, "builtin_names", pos))
            {
                json_helper::skip_ws(content, pos);
                if (pos < content.size() && content[pos] == '{')
                {
                    pos++; // skip {
                    while (pos < content.size())
                    {
                        json_helper::skip_ws(content, pos);
                        if (content[pos] == '}')
                        {
                            pos++;
                            break;
                        }

                        // Read scope key
                        std::string scope = json_helper::read_string(content, pos);
                        json_helper::skip_ws(content, pos);
                        if (pos < content.size() && content[pos] == ':')
                            pos++;
                        json_helper::skip_ws(content, pos);

                        // Read array of names
                        auto names = json_helper::parse_string_array(content, pos);
                        for (auto &name : names)
                        {
                            theme.builtinNames[name] = scope;
                        }
                        json_helper::skip_comma(content, pos);
                    }
                }
            }
        }

        theme.loaded = true;
        std::cout << "[theme] Loaded " << jsonPath
                  << " — " << theme.ui.size() << " UI colors, "
                  << theme.scopeColors.size() << " token colors, "
                  << theme.tokenTypeMap.size() << " type mappings, "
                  << theme.builtinNames.size() << " builtin names\n";

        return theme;
    }

    // ─── Theme discovery: find terminal_colors.json ──────────────────────────

    inline ThemeData loadDefaultTheme()
    {
        // Search order:
        // 1. ~/.config/xell/terminal_colors.json (user override)
        // 2. ~/.local/share/xell/terminal_colors.json
        // 3. executable-relative assets/share paths
        // 4. system install paths
        // 5. local working-directory files (dev fallback)
        // 6. Built-in defaults (no file)

        std::vector<std::string> searchPaths;

        const char *home = std::getenv("HOME");
        if (home)
        {
            searchPaths.push_back(std::string(home) + "/.config/xell/terminal_colors.json");
            searchPaths.push_back(std::string(home) + "/.local/share/xell/terminal_colors.json");
        }

        // Search relative to executable
        char *base = SDL_GetBasePath();
        if (base)
        {
            searchPaths.push_back(std::string(base) + "assets/terminal_colors.json");
            searchPaths.push_back(std::string(base) + "../share/xell-terminal/terminal_colors.json");
            searchPaths.push_back(std::string(base) + "../share/xell/terminal_colors.json");
            SDL_free(base);
        }

        searchPaths.push_back("/usr/local/share/xell/terminal_colors.json");
        searchPaths.push_back("/usr/local/share/xell-terminal/terminal_colors.json");
        searchPaths.push_back("/usr/share/xell-terminal/terminal_colors.json");

        // Dev/local fallback paths (lowest priority)
        searchPaths.push_back("terminal_colors.json");
        searchPaths.push_back("assets/terminal_colors.json");

        for (auto &path : searchPaths)
        {
            if (fs::exists(path))
                return loadTheme(path);
        }

        std::cout << "[theme] No terminal_colors.json found — using built-in defaults\n";

        // Return empty theme with loaded=false — caller will use hardcoded defaults
        return ThemeData{};
    }

    // ─── Convenience: get UI color with fallback ─────────────────────────────

    inline Color getUIColor(const ThemeData &theme, const std::string &key, Color fallback)
    {
        auto it = theme.ui.find(key);
        return it != theme.ui.end() ? it->second : fallback;
    }

    // ─── Convenience: get token style for a scope ────────────────────────────

    inline ThemeData::TokenStyle getTokenStyle(const ThemeData &theme, const std::string &scope)
    {
        auto it = theme.scopeColors.find(scope);
        if (it != theme.scopeColors.end())
            return it->second;

        // Fallback: try progressively shorter scope prefixes
        // e.g. "support.function.math.xell" → "support.function.xell"
        std::string s = scope;
        while (true)
        {
            auto lastDot = s.rfind('.');
            if (lastDot == std::string::npos)
                break;
            // Remove last segment before ".xell"
            auto prevDot = s.rfind('.', lastDot - 1);
            if (prevDot == std::string::npos)
                break;
            s = s.substr(0, prevDot) + s.substr(lastDot);
            auto it2 = theme.scopeColors.find(s);
            if (it2 != theme.scopeColors.end())
                return it2->second;
        }

        return {Color::default_fg(), false, false};
    }

} // namespace xterm
