// ═══════════════════════════════════════════════════════════
// Xell Completion Items — DYNAMICALLY LOADED
// ═══════════════════════════════════════════════════════════
//
// All data loaded from language_data.json (generated by gen_xell_grammar.py).
// DO NOT hardcode keyword or builtin lists here.
//

import { CompletionItem, CompletionItemKind } from 'vscode-languageserver/node';
import rawLangData from './language_data.json';

// ── Types ────────────────────────────────────────────────

interface LangKeyword {
    name: string;
    kind: string;      // "Keyword" | "Constant"
    detail: string;
    hover?: { sig: string; detail: string; params?: string[] };
}

interface LangBuiltin {
    name: string;
    category: string;
    kind: string;       // "Function"
    hover?: { sig: string; detail: string; params?: string[] };
}

interface LanguageData {
    keywords: LangKeyword[];
    builtins: LangBuiltin[];
    blockKeywords: string[];
    allKeywordNames: string[];
}

const LANG_DATA: LanguageData = rawLangData as LanguageData;

// ── Build completions from loaded data ───────────────────

function buildKeywordCompletions(): CompletionItem[] {
    return LANG_DATA.keywords.map(kw => ({
        label: kw.name,
        kind: kw.kind === 'Constant' ? CompletionItemKind.Constant : CompletionItemKind.Keyword,
        detail: kw.detail,
        data: `kw_${kw.name}`
    }));
}

function buildBuiltinCompletions(): CompletionItem[] {
    return LANG_DATA.builtins.map(b => ({
        label: b.name,
        kind: CompletionItemKind.Function,
        detail: b.hover?.detail || `${b.category} function`,
        data: `fn_${b.name}`
    }));
}

export const XELL_KEYWORDS: CompletionItem[] = buildKeywordCompletions();
export const XELL_BUILTINS: CompletionItem[] = buildBuiltinCompletions();
export const ALL_COMPLETIONS: CompletionItem[] = [...XELL_KEYWORDS, ...XELL_BUILTINS];

// Export the raw data for use by hover, diagnostics, etc.
export { LANG_DATA };
export type { LanguageData, LangKeyword, LangBuiltin };
