// ═══════════════════════════════════════════════════════════
// Xell Hover / Signature Information — DYNAMICALLY LOADED
// ═══════════════════════════════════════════════════════════
//
// All data loaded from language_data.json (generated by gen_xell_grammar.py).
// DO NOT hardcode hover/signature data here.
//

import { LANG_DATA } from './completions';

export interface HoverEntry {
    signature: string;
    detail: string;
    params?: string[];
}

function buildHoverInfo(): Record<string, HoverEntry> {
    const info: Record<string, HoverEntry> = {};

    // Load keyword hover info
    for (const kw of LANG_DATA.keywords) {
        if (kw.hover) {
            info[kw.name] = {
                signature: kw.hover.sig,
                detail: kw.hover.detail,
                params: kw.hover.params
            };
        }
    }

    // Load builtin hover info
    for (const b of LANG_DATA.builtins) {
        if (b.hover) {
            info[b.name] = {
                signature: b.hover.sig,
                detail: b.hover.detail,
                params: b.hover.params
            };
        }
    }

    return info;
}

export const HOVER_INFO: Record<string, HoverEntry> = buildHoverInfo();

