#pragma once

// =============================================================================
// snippet_engine.hpp — Snippet expansion engine for the Xell Terminal IDE
// =============================================================================
// Parses VSCode-format snippet files (xell.json) at runtime.
// Provides snippet expansion with tab stop navigation.
//
// Snippet format (from xell.json, generated by gen_xell_grammar.py):
//   "prefix": "fn"
//   "body": ["fn ${1:name}(${2:params}) :", "    ${3:# body}", ";"]
//   "description": "Define a new function"
//
// Tab stops: ${N:placeholder} or $N or $0 (final cursor)
// =============================================================================

#include <string>
#include <vector>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <iostream>
#include <unordered_map>

namespace xterm
{

    // ─── Tab stop: a fillable placeholder in an expanded snippet ─────────

    struct TabStop
    {
        int index;  // tab stop number (1, 2, ... 0 = final)
        int line;   // relative line within snippet (0-based)
        int col;    // column within that line
        int length; // length of placeholder text
        std::string placeholder;
    };

    // ─── Snippet definition (parsed from JSON) ──────────────────────────

    struct SnippetDef
    {
        std::string prefix;                 // trigger text (e.g. "fn", "for")
        std::string description;            // short description
        std::vector<std::string> bodyLines; // raw body lines with ${N:...} markers
    };

    // ─── Active snippet (being expanded/filled in editor) ───────────────

    struct ActiveSnippet
    {
        std::vector<std::string> lines; // expanded text (placeholders filled)
        std::vector<TabStop> tabStops;  // sorted by index
        int currentStop = 0;            // which tab stop is selected
        int startLine = 0;              // buffer line where snippet starts
        int startCol = 0;               // buffer col where snippet starts
        bool active = false;

        // Get the current tab stop (or null)
        const TabStop *current() const
        {
            if (!active || tabStops.empty() || currentStop >= (int)tabStops.size())
                return nullptr;
            return &tabStops[currentStop];
        }

        // Advance to next tab stop. Returns false if done.
        bool nextStop()
        {
            if (!active || tabStops.empty())
                return false;
            currentStop++;
            if (currentStop >= (int)tabStops.size())
            {
                active = false;
                return false;
            }
            return true;
        }

        // Go to previous tab stop.
        bool prevStop()
        {
            if (!active || currentStop <= 0)
                return false;
            currentStop--;
            return true;
        }
    };

    // ─── Snippet Engine ─────────────────────────────────────────────────

    class SnippetEngine
    {
    public:
        // Load snippets from a VSCode-format JSON file (xell.json)
        void loadSnippets(const std::string &path)
        {
            snippets_.clear();

            std::ifstream file(path);
            if (!file.is_open())
            {
                std::cerr << "[snippets] cannot open: " << path << "\n";
                return;
            }

            std::string content((std::istreambuf_iterator<char>(file)),
                                std::istreambuf_iterator<char>());

            std::cerr << "[snippets] file size: " << content.size() << " bytes\n";
            parseSnippetJSON(content);
            std::cerr << "[snippets] parsed: " << snippets_.size() << " snippets\n";
        }

        // Get all loaded snippets
        const std::vector<SnippetDef> &snippets() const { return snippets_; }

        // Find a snippet by prefix
        const SnippetDef *findByPrefix(const std::string &prefix) const
        {
            for (auto &s : snippets_)
            {
                if (s.prefix == prefix)
                    return &s;
            }
            return nullptr;
        }

        // Get snippets matching a prefix (fuzzy)
        std::vector<const SnippetDef *> match(const std::string &prefix) const
        {
            std::vector<const SnippetDef *> results;
            if (prefix.empty())
                return results;

            std::string lp = toLower(prefix);
            for (auto &s : snippets_)
            {
                std::string ls = toLower(s.prefix);
                if (ls.substr(0, lp.size()) == lp)
                    results.push_back(&s);
            }
            return results;
        }

        // Expand a snippet definition into an ActiveSnippet.
        // Returns the text to insert and the tab stops.
        ActiveSnippet expand(const SnippetDef &def, int insertLine, int insertCol) const
        {
            ActiveSnippet result;
            result.startLine = insertLine;
            result.startCol = insertCol;
            result.active = true;
            result.currentStop = 0;

            // Parse body lines, extracting tab stops and replacing with placeholders
            for (int lineIdx = 0; lineIdx < (int)def.bodyLines.size(); lineIdx++)
            {
                const std::string &raw = def.bodyLines[lineIdx];
                std::string expanded;
                size_t pos = 0;

                while (pos < raw.size())
                {
                    // Look for ${N:placeholder} or $N
                    if (raw[pos] == '$' && pos + 1 < raw.size())
                    {
                        if (raw[pos + 1] == '{')
                        {
                            // ${N:placeholder}
                            size_t close = raw.find('}', pos + 2);
                            if (close != std::string::npos)
                            {
                                std::string inner = raw.substr(pos + 2, close - pos - 2);
                                // Parse "N:placeholder" or just "N"
                                size_t colon = inner.find(':');
                                int idx = 0;
                                std::string placeholder;
                                if (colon != std::string::npos)
                                {
                                    idx = safeStoi(inner.substr(0, colon));
                                    placeholder = inner.substr(colon + 1);
                                }
                                else
                                {
                                    idx = safeStoi(inner);
                                }

                                // Compute column offset
                                int col = (int)expanded.size();
                                if (lineIdx == 0)
                                    col += insertCol;

                                TabStop ts;
                                ts.index = idx;
                                ts.line = lineIdx;
                                ts.col = col;
                                ts.length = (int)placeholder.size();
                                ts.placeholder = placeholder;
                                result.tabStops.push_back(ts);

                                expanded += placeholder;
                                pos = close + 1;
                                continue;
                            }
                        }
                        else if (std::isdigit(raw[pos + 1]))
                        {
                            // $N (no placeholder)
                            size_t end = pos + 1;
                            while (end < raw.size() && std::isdigit(raw[end]))
                                end++;
                            int idx = safeStoi(raw.substr(pos + 1, end - pos - 1));

                            int col = (int)expanded.size();
                            if (lineIdx == 0)
                                col += insertCol;

                            TabStop ts;
                            ts.index = idx;
                            ts.line = lineIdx;
                            ts.col = col;
                            ts.length = 0;
                            ts.placeholder = "";
                            result.tabStops.push_back(ts);

                            pos = end;
                            continue;
                        }
                    }

                    expanded += raw[pos];
                    pos++;
                }

                result.lines.push_back(expanded);
            }

            // Sort tab stops: $1, $2, ... $0 last (final cursor)
            std::sort(result.tabStops.begin(), result.tabStops.end(),
                      [](const TabStop &a, const TabStop &b)
                      {
                          // $0 goes last
                          if (a.index == 0 && b.index != 0)
                              return false;
                          if (a.index != 0 && b.index == 0)
                              return true;
                          return a.index < b.index;
                      });

            return result;
        }

        // Build the full insertion text from an expanded snippet
        static std::string buildInsertText(const ActiveSnippet &snippet)
        {
            std::string result;
            for (int i = 0; i < (int)snippet.lines.size(); i++)
            {
                if (i > 0)
                    result += '\n';
                result += snippet.lines[i];
            }
            return result;
        }

        // Get the first line preview of a snippet (for ghost text)
        std::string getPreview(const SnippetDef &def) const
        {
            if (def.bodyLines.empty())
                return "";

            // Strip tab stop markers from first line for preview
            std::string preview;
            const std::string &raw = def.bodyLines[0];
            size_t pos = 0;
            while (pos < raw.size())
            {
                if (raw[pos] == '$' && pos + 1 < raw.size())
                {
                    if (raw[pos + 1] == '{')
                    {
                        size_t close = raw.find('}', pos + 2);
                        if (close != std::string::npos)
                        {
                            std::string inner = raw.substr(pos + 2, close - pos - 2);
                            size_t colon = inner.find(':');
                            if (colon != std::string::npos)
                                preview += inner.substr(colon + 1);
                            pos = close + 1;
                            continue;
                        }
                    }
                    else if (std::isdigit(raw[pos + 1]))
                    {
                        size_t end = pos + 1;
                        while (end < raw.size() && std::isdigit(raw[end]))
                            end++;
                        pos = end;
                        continue;
                    }
                }
                preview += raw[pos];
                pos++;
            }
            return preview;
        }

    private:
        std::vector<SnippetDef> snippets_;

        static std::string toLower(const std::string &s)
        {
            std::string result = s;
            for (auto &c : result)
                c = std::tolower(c);
            return result;
        }

        static int safeStoi(const std::string &s)
        {
            try
            {
                return std::stoi(s);
            }
            catch (...)
            {
                return 0;
            }
        }

        // ── Minimal JSON parser for VSCode snippet format ────────────

        void parseSnippetJSON(const std::string &json)
        {
            // The JSON is a top-level object where each key is a snippet name.
            // Each value has "prefix", "body" (string or array), "description".
            // We parse with a simple state machine.

            size_t pos = 0;
            skipWhitespace(json, pos);
            if (pos >= json.size() || json[pos] != '{')
            {
                std::cerr << "[snippets] JSON does not start with {, pos=" << pos
                          << " size=" << json.size();
                if (pos < json.size())
                    std::cerr << " char=" << (int)(unsigned char)json[pos];
                std::cerr << "\n";
                return;
            }
            pos++; // skip opening {

            while (pos < json.size())
            {
                skipWhitespace(json, pos);
                if (pos >= json.size() || json[pos] == '}')
                    break;

                if (json[pos] == ',')
                {
                    pos++;
                    continue;
                }

                // Read snippet name (key)
                std::string snippetName = readString(json, pos);
                if (snippetName.empty())
                {
                    std::cerr << "[snippets] empty name at pos=" << pos << "\n";
                    break;
                }

                skipWhitespace(json, pos);
                if (pos >= json.size() || json[pos] != ':')
                {
                    std::cerr << "[snippets] expected : after '" << snippetName
                              << "' at pos=" << pos << "\n";
                    break;
                }
                pos++; // skip :

                // Read the snippet object
                SnippetDef def;
                if (!parseSnippetObject(json, pos, def))
                {
                    std::cerr << "[snippets] failed to parse object for '"
                              << snippetName << "' at pos=" << pos << "\n";
                    break;
                }

                if (!def.prefix.empty() && !def.bodyLines.empty())
                    snippets_.push_back(def);
            }
        }

        bool parseSnippetObject(const std::string &json, size_t &pos, SnippetDef &def)
        {
            skipWhitespace(json, pos);
            if (pos >= json.size() || json[pos] != '{')
                return false;
            pos++; // skip {

            while (pos < json.size())
            {
                skipWhitespace(json, pos);
                if (pos >= json.size())
                    return false;
                if (json[pos] == '}')
                {
                    pos++;
                    return true;
                }
                if (json[pos] == ',')
                {
                    pos++;
                    continue;
                }

                std::string key = readString(json, pos);
                skipWhitespace(json, pos);
                if (pos >= json.size() || json[pos] != ':')
                    return false;
                pos++; // skip :
                skipWhitespace(json, pos);

                if (key == "prefix")
                {
                    def.prefix = readString(json, pos);
                }
                else if (key == "description")
                {
                    def.description = readString(json, pos);
                }
                else if (key == "body")
                {
                    if (pos < json.size() && json[pos] == '[')
                    {
                        // Array of lines
                        pos++; // skip [
                        while (pos < json.size())
                        {
                            skipWhitespace(json, pos);
                            if (pos >= json.size() || json[pos] == ']')
                            {
                                pos++;
                                break;
                            }
                            if (json[pos] == ',')
                            {
                                pos++;
                                continue;
                            }
                            std::string line = readString(json, pos);
                            def.bodyLines.push_back(line);
                        }
                    }
                    else if (pos < json.size() && json[pos] == '"')
                    {
                        // Single string body
                        std::string body = readString(json, pos);
                        def.bodyLines.push_back(body);
                    }
                    else
                    {
                        skipValue(json, pos);
                    }
                }
                else
                {
                    // Unknown key — skip value
                    skipValue(json, pos);
                }
            }
            return false;
        }

        static void skipWhitespace(const std::string &s, size_t &pos)
        {
            while (pos < s.size() && (s[pos] == ' ' || s[pos] == '\t' || s[pos] == '\n' || s[pos] == '\r'))
                pos++;
        }

        static std::string readString(const std::string &s, size_t &pos)
        {
            skipWhitespace(s, pos);
            if (pos >= s.size() || s[pos] != '"')
                return "";
            pos++; // skip opening "

            std::string result;
            while (pos < s.size())
            {
                if (s[pos] == '\\' && pos + 1 < s.size())
                {
                    char next = s[pos + 1];
                    if (next == '"')
                        result += '"';
                    else if (next == '\\')
                        result += '\\';
                    else if (next == 'n')
                        result += '\n';
                    else if (next == 't')
                        result += '\t';
                    else
                    {
                        result += '\\';
                        result += next;
                    }
                    pos += 2;
                }
                else if (s[pos] == '"')
                {
                    pos++; // skip closing "
                    return result;
                }
                else
                {
                    result += s[pos];
                    pos++;
                }
            }
            return result;
        }

        // Skip a JSON value (string, number, array, object, bool, null)
        static void skipValue(const std::string &s, size_t &pos)
        {
            skipWhitespace(s, pos);
            if (pos >= s.size())
                return;

            if (s[pos] == '"')
            {
                readString(s, pos);
            }
            else if (s[pos] == '{')
            {
                int depth = 1;
                pos++;
                while (pos < s.size() && depth > 0)
                {
                    if (s[pos] == '{')
                        depth++;
                    else if (s[pos] == '}')
                        depth--;
                    else if (s[pos] == '"')
                    {
                        readString(s, pos);
                        continue;
                    }
                    pos++;
                }
            }
            else if (s[pos] == '[')
            {
                int depth = 1;
                pos++;
                while (pos < s.size() && depth > 0)
                {
                    if (s[pos] == '[')
                        depth++;
                    else if (s[pos] == ']')
                        depth--;
                    else if (s[pos] == '"')
                    {
                        readString(s, pos);
                        continue;
                    }
                    pos++;
                }
            }
            else
            {
                // Number, bool, null — read until delimiter
                while (pos < s.size() && s[pos] != ',' && s[pos] != '}' && s[pos] != ']')
                    pos++;
            }
        }
    };

} // namespace xterm
